development:
  password: 16ef663594568325d64408ebcdeef528
  theme_id: "123"
  store: https://noya-trial.myshopify.com
  proxy: http://localhost:3000
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json
production:
  password: 16ef663594568325d64408ebcdeef528
  theme_id: "456"
  store: https://noya-trial.myshopify.com
  timeout: 60s
  readonly: true
test:
  password: 16ef663594568325d64408ebcdeef528
  theme_id: "789"
  store: https://noya-trial.myshopify.com
  ignores: ignore.txt